---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 8
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: 
          requests: 
            memory: "256Mi"
            cpu: "500"
          limits:
            memory: "256Mi"
            cpu: "500"
        ports:
        - containerPort: 80