---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-big-deployment
spec:
  selector:
    matchLabels:
      app: nginx-big
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-big
    spec:
      containers:
      - name: nginx-big
        image: nginx
        resources: 
          requests: 
            memory: "8192Mi"
            cpu: "4000m"
          limits:
            memory: "8192Mi"
            cpu: "4000m"
        ports:
        - containerPort: 80